import 'feature/page_index.dart';
import 'setting/page/index.dart';

final routeTable = {
  '/home': (context) => const HomePage(),
  '/report': (context) => const DailyReportPage(),
  '/login': (context) => const LoginPage(),
  '/welcome': (context) => const WelcomePage(),
  '/about': (context) => const AboutPage(),
  '/expense': (context) => const ExpensePage(),
  '/connectivity': (context) => const ConnectivityPage(),
  '/campusCard': (context) => const CampusCardPage(),
  '/electricity': (context) => const ElectricityPage(),
  '/score': (context) => const ScorePage(),
  '/office': (context) => const OfficePage(),
  '/game': (context) => const GamePage(),
  '/game/2048': (context) => Game2048Page(),
  '/game/wordle': (context) => const WordlePage(),
  '/game/composeSit': (context) => const ComposeSitPage(),
  '/wiki': (context) => WikiPage(),
  '/library': (context) => const LibraryPage(),
  '/library/appointment': (context) => const LibraryAppointmentPage(),
  '/market': (context) => const MarketPage(),
  '/timetable': (context) => const TimetablePage(),
  '/timetable/import': (context) => const TimetableImportPage(),
  '/setting': (context) => SettingPage(),
  '/feedback': (context) => const FeedbackPage(),
  '/notice': (context) => const NoticePage(),
  '/contact': (context) => const ContactPage(),
  '/bulletin': (context) => const BulletinPage(),
  '/mail': (context) => const MailPage(),
  '/night': (context) => const NightPage(),
  '/event': (context) => const EventPage(),
  '/lost-found': (context) => const LostFoundPage(),
  '/classroom': (context) => const ClassroomPage(),
  '/exam': (context) => const ExamPage(),
  '/egg': (context) => const EggPage(),
  '/bbs': (context) => const BbsPage(),
};
